//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESA
    {
        public int NOMBRE_PROD { get; set; }
        public string CAP_MAXIMA { get; set; }
        public string AREA { get; set; }
        public string TURBINAS { get; set; }
    }
}
