//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONA
    {
        public int CODIGO { get; set; }
        public int CODIGO_PROV { get; set; }
        public string CONS_PROMEDIO { get; set; }
        public int NUM_PART { get; set; }
        public int NUM_EMP { get; set; }
        public int NUM_INST { get; set; }
    }
}
